### PR TITLE
Fix bar series distance calculation

### LINKED ISSUE #68: Bar widths incorrectly calculated for bar charts
The bar widths seem to be incorrectly calculated

image

The algorithm shouldn't be producing widths where there would be bars that overlap.

### PR DESCRIPTION
**Pull request by chrisirhc**
The bar series distance calculation should calculate the minimum distance between the points, and use that to create bars that don't overlap.

- Add failing test cases

Fixes #68

### CODE REVIEW

File: src/lib/utils/scales-utils.js [hunk 1]
```diff
@@ -78,24 +78,26 @@ const SCALE_FUNCTIONS = {
...
  * the index of the element, where the smallest distance was found.
+ * It returns the first occurrence of i where
+ * `scale(value[i]) - scale(value[i - 1])` is minimal
  * @param {Array} values Array of values.
  * @param {Object} scaleObject Scale object.
  * @returns {number} Index of an element where the smallest distance was found.
  * @private
  */
-function _getSmallestDistanceIndex(values, scaleObject) {
+export function _getSmallestDistanceIndex(values, scaleObject) {
```
Comment (bulyonov) [inline src/lib/utils/scales-utils.js]: Private functions cannot be exported.

Comment (chrisirhc) [inline src/lib/utils/scales-utils.js]: I think we should strive for correctness and stability. I've seen private APIs in the wild, they're usually marked with underscore. If users choose to rely on these methods, we make no guarantees, and it's indicated here that it's private API.

**Comment by bulyonov** [comment]
LGTM, @chrisirhc , I'm merging that.

**Comment by SimpleCookie** [comment]
This issue appear to still be relevant in the latest version, including the main example at https://uber.github.io/react-vis/examples/showcases/plots

@chrisirhc @bulyonov
