### PR TITLE
Fix VerticalRectSeries - single time slice expands xDomain

### LINKED ISSUE #443: VerticalRectSeries - single time slice expands xDomain
Edge case with `VerticalRectSeries` - when there is a single [x0, x] pair, the x domain is expanded out far beyond the realm of the data (~1970 - ~2070, which I think is the default in d3-axis?) 

I assume this occurs with other series types too, although haven't tested for those.

The issue still occurs when you specify an `xDomain` on `XYPlot`.

## Example

```jsx
<XYPlot
  width={300}
  height={300}
  xType="time"
  stackBy="y">
  <VerticalGridLines />
  <HorizontalGridLines />
  <XAxis />
  <YAxis />
  <VerticalRectSeries
    data={[
      {x0: new Date(2015, 0, 1).valueOf(), x: new Date(2015, 1, 1).valueOf(), y: 16}
    ]}
  />
  <VerticalRectSeries
    data={[
      {x0: new Date(2015, 0, 1).valueOf(), x: new Date(2015, 1, 1).valueOf(), y: 12}
    ]}/>
</XYPlot>
```

## Output

screen shot 2017-05-31 at 9 47 35 am

### PR DESCRIPTION
**Pull request by sandiiarov**
Fixes #443

### CODE REVIEW

File: src/utils/scales-utils.js [hunk 1]
```diff
@@ -363,7 +363,13 @@ function _computeScaleDistance(values, domain, bestDistIndex, scaleFn) {
  */
 export function _getScaleDistanceAndAdjustedDomain(data, scaleObject) {
   const {attr, domain} = scaleObject;
-  const values = getUniquePropertyValues(data, attr);
+
+  let values = getUniquePropertyValues(data, attr);
```
Comment (mcnuttandrew) [inline src/utils/scales-utils.js]: Can you make this a helper function to avoid the let?

File: src/utils/scales-utils.js [hunk 2]
```diff
@@ -363,7 +363,13 @@ function _computeScaleDistance(values, domain, bestDistIndex, scaleFn) {
...
+  // Fix time scale if a data has only one value.
+  if (scaleObject.type === TIME_SCALE_TYPE && values.length === 1) {
+    values = [data[0].x0, ...values];
```
Comment (mcnuttandrew) [inline src/utils/scales-utils.js]: Should make sure the thing you are looking at has an x0, e.g. What if there is a y0, as is the case for horizontalRectSeries?

File: src/utils/scales-utils.js [hunk 3]
```diff
@@ -367,7 +367,7 @@ export function _getScaleDistanceAndAdjustedDomain(data, scaleObject) {
   const values = getUniquePropertyValues(data, attr);
   // Fix time scale if a data has only one value.
   if (scaleObject.type === TIME_SCALE_TYPE && values.length === 1) {
-    values.unshift(data[0].y0 || data[0].x0);
+    values.unshift(data[0][`${scaleObject.attr}0`]);
```
Comment (mcnuttandrew) [inline src/utils/scales-utils.js]: I still think this would be better as a helper method, it would aid in code ledgibility, would guarantee we have room to grow if there are more cases, and, most importantly, would avoid mutating data.

File: src/utils/scales-utils.js [hunk 4]
```diff
@@ -363,7 +363,13 @@ function _computeScaleDistance(values, domain, bestDistIndex, scaleFn) {
  */
 export function _getScaleDistanceAndAdjustedDomain(data, scaleObject) {
   const {attr, domain} = scaleObject;
+
   const values = getUniquePropertyValues(data, attr);
+  // Fix time scale if a data has only one value.
+  if (scaleObject.type === TIME_SCALE_TYPE && values.length === 1) {
```
Comment (mcnuttandrew) [inline src/utils/scales-utils.js]: I still think this should be a helper method. It'll make the code easier to read and can avoid mutating data

File: src/utils/scales-utils.js [hunk 5]
```diff
@@ -363,7 +363,13 @@ function _computeScaleDistance(values, domain, bestDistIndex, scaleFn) {
...
+    values.unshift(data[0][`${scaleObject.attr}0`]);
+  }
+
```
Comment (mcnuttandrew) [inline src/utils/scales-utils.js]: Aren't there cases when an att won't have a zero case?

File: src/utils/scales-utils.js (hunk 3 above)
Comment (mcnuttandrew) [inline src/utils/scales-utils.js]: Sorry about double comment, github mobile ain't great

File: src/utils/scales-utils.js (hunk 5 above)
Comment (sandiiarov) [inline src/utils/scales-utils.js]: I am not sure.

But if we try to pass a data without x0 or y0

screen shot 2017-06-09 at 3 16 01 pm

we get these errors:

screen shot 2017-06-09 at 3 14 39 pm

Comment (samhogg) [inline src/utils/scales-utils.js]: @sandiiarov try using a `VerticalBarSeries` with just an `[x,y]` tuple - `VerticalRectSeries` requires an `x0`

Comment (sandiiarov) [inline src/utils/scales-utils.js]: With `VerticalRectSeries` I get the same errors

File: src/utils/scales-utils.js (hunk 3 above)
Comment (sandiiarov) [inline src/utils/scales-utils.js]: Hmm. What do you think about this:

**Comment by mcnuttandrew** [comment]
Sorry for the long delay, was on vacation. Looks good!
